project-flotta/project-flotta.github.io

- _posts/2022-03-02-getting-started-project-flotta.markdown
Add short paragraph on difference between OCP and K8S
in flotta-operator.yaml file.
Add definition of OCP and CRD acronyms to the first occurence.
Add link to CRDs kubernetes website.
Use numbered list to describe flotta CRDs.
> Update getting started guide

- _posts/2022-04-08-introducing-device-groups.markdown
- _posts/2022-04-08-introducing-device-sets.markdown
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
> Edge Device Groups introduction blog post

- _posts/2022-04-11-writing-metrics-to-control-plane.markdown
https://issues.redhat.com/browse/ECOPROJECT-697
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
> blog: metrics collection

- _layouts/post.html
- _posts/2022-04-08-introducing-device-sets.markdown
- _posts/2022-04-11-writing-metrics-to-control-plane.markdown
- _posts/2022-04-15-flotta-and-raspberry-pi.markdown
- assets/scss/_custom.scss
- assets/scss/_typography.scss
Fixed the font size in the whole project, now headings are much better.
Fixed some blog post headings to correct ones <h1> <h2> etc..
Fixed list on post, now are renderered correctly.
> Blog: Fix headings/list and font-size

- _data/documentation/latest.yaml
- documentation/latest/gsg/minikube.md
- documentation/latest/gsg/running_workloads.md
> GSG: Add how to get started with minikube

- _includes/features-section.html
> Add flotta demo on index page

- _data/settings.yml
> Add social media accounts

- documentation/latest/operations/requirements.md
> Doc: Added system requirements

- documentation/latest/gsg/kind.md
> Doc: Added kind demo

- _data/documentation/latest.yaml
- _data/settings.yml
- documentation/latest/intro/concepts.md
- documentation/latest/intro/overview.md
> doc: Add concepts page

- documentation/latest/operations/deployment_options.md
- documentation/latest/operations/requirements.md
- Enable a comment on why is optional and when is needed.
- Added missing env variable deployment option. 
> Doc: system requirements fixes

- _data/documentation/latest.yaml
- documentation/latest/dev/profiling.md
- documentation/latest/operations/configuration.md
> Doc: Added the latest missing docs from operator

- _data/documentation/latest.yaml
- documentation/latest/dev/guide.md
- documentation/latest/dev/installation.md
The first section for dev guide: 
I'm using the following PR here that are not yet merged: 
- https://github.com/project-flotta/flotta-device-worker/pull/146
- https://github.com/project-flotta/flotta-operator/pull/217
> Doc: Add fisrt dev guide examples

- _posts/2022-03-02-getting-started-project-flotta.markdown
> Update operator version

- documentation/latest/operations/observability.md
> Fix grafana paths

- documentation/latest/dev/installation.md
Updated the installation guide after changes in `make get-certs` and fixed a few typos.
Signed-off-by: arielireni <aireni@redhat.com>
> Update manual installation guide

- _data/settings.yml
- documentation/latest/intro/concepts.md
- documentation/latest/intro/overview.md
> Update site to use Flotta terminology

- _posts/2022-03-02-getting-started-project-flotta.markdown
- documentation/latest/operations/deployment_options.md
> Disable OBC auto-create by default

- README.md
> Add step for running the site locally to README

- documentation/latest/gsg/kind.md
Found this when I was reading the doc. Trying to fix, thanks!
> Fix a typo

- documentation/latest/dev/installation.md
> Troubleshooting: Remove edgedevice CR of unavailable device

- documentation/latest/operations/observability.md
> Rename EdgeDeviceGroup to its updated name

- _posts/2022-03-02-getting-started-project-flotta.markdown
> Update getting started CRDs

- _posts/2022-03-07-using-private-image-repositories.markdown
- _posts/2022-04-10-using-log-collection.markdown
> Use EdgeWorkload instead of EdgeDeployment

- documentation/latest/gsg/kind.md
- documentation/latest/gsg/minikube.md
- documentation/v0_1_0/gsg/kind.md
- documentation/v0_1_0/gsg/minikube.md
on v0.1.0 -> Using the right branch, if not will fail. 
on master -> Using the right deploy image, if not ImgPullerror happen.
> Fix GSG deploy options

- _includes/footer.html
- _includes/head.html
We would like to track how people are using our website.
Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>
> Adding analytics

- documentation/latest/operations/data_upload.md
Updates documentation to reflect the new schema changes for data transfer. Pending of https://github.com/project-flotta/flotta-device-worker/pull/161 to be merged first.
> add bidirectional data transfer

- README.md
- documentation/v0_1_0/gsg/kind.md
- documentation/v0_1_0/gsg/minikube.md
- documentation/v0_1_0/gsg/ocp.md
> Doc: Fix labels on stable documentation

- documentation/latest/dev/installation.md
> Doc: rootless podman documentation

- _posts/2022-05-23-deploy-agent-on-fedora-coreos.markdown
Signed-off-by: Cosmin Tupangiu <cosmin@redhat.com>
> add blog on how to deploy agent on coreos

- documentation/latest/dev/installation.md
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>
> Fix: Add instruction to run Edge API

- README.md
- documentation/v0_1_0/operations/api.html
> Fix swagger API URL for v0.1.0

- _posts/2022-04-15-flotta-and-raspberry-pi.markdown
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
> Add port forwarding instructions for Flotta v0.1.0

- documentation/latest/operations/requirements.md
> Bump podman requirement to 4.0

- documentation/latest/dev/installation.md
- documentation/latest/operations/requirements.md
> Deprecate agent support for fc35

- _posts/2022-07-20-developer-cli.markdown
Signed-off-by: arielireni <aireni@redhat.com>
> Add flotta-dev-cli post

- _data/documentation/latest.yaml
- _posts/2022-07-22-accessing-host-devices-in-flotta.markdown
- documentation/latest/operations/configuration.md
- documentation/latest/operations/host_devices.md
Added access to host devices related documentation:
* Blog post
* Documentation
Pending on https://github.com/project-flotta/flotta-device-worker/pull/212 to be merged first.
> Added blog post host devices

- documentation/latest/intro/overview.md
> Update overview diagram

- documentation/latest/intro/overview.md
> Render overview diagram to fit the page

- documentation/latest/intro/overview.md
- documentation/v0_2_0/intro/overview.md
> Add OS lifecycle description

- _posts/2022-07-20-developer-cli.markdown
> Add troubleshooting section to flotta-dev-cli

- documentation/latest/dev/guide.md
Signed-off-by: arielireni <aireni@redhat.com>
> Add a section about flotta-dev-cli to the developer guide

- _posts/2022-07-20-developer-cli.markdown
> Added  another command for tab completion
